### ISSUE TITLE
(Feedback from Ryan Hollins ) Add Puerto Rice Vertical Datum 2002 (PRVD02) to "datum" options

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/WaveLabServices#3]
![image](https://user-images.githubusercontent.com/35497731/57886192-454d5e00-77f2-11e9-85b3-bd85d8e9dc01.png)
In the configuration for each procedure

**Comment by jknewson** [comment]
fixed with latest [commit ](https://github.com/USGS-WiM/WaveLabServices/commit/43f52594203ab80c4b5d584b27b35dc9996dacf4)
