### ISSUE TITLE
Remove STNPseudoProd from the nightly shutdown script

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/WaveLabServices#6]
The Wavelab services are hosted there. It's an ec2 instance on the main? account.

We want to leave it up for demos and training at the Data Training Workshop in Ohio next week.

**Comment by aaronstephenson** [comment]
@lprivette I don't see that instance in the nightly shutdown list. But it's also not in the daily startup list, either. So I think what we need is to just add it to the startup list, yes? I'll do that now.

**Comment by lprivette** [comment]
Thanks Aaron
