### ISSUE TITLE
Remove wavelab (stnpsuedo) from daily startup and add it to nightly shutdown

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/WaveLabServices#7]
Data Training Workshop has concluded.

**Comment by aaronstephenson** [comment]
Well this is weird. I'm looking at the start and stop instance ID lists and I'm seeing this instance already in the stop list but not in the start list. Has someone been manually starting it each morning @lprivette @HansVraga @jknewson?

**Comment by aaronstephenson** [comment]
Also, should we rename this instance to just "STNWaveLab" or something more apropos?

**Comment by aaronstephenson** [comment]
Well the instance ID was still in the start list ¯\_(ツ)_/¯ so I removed it.
